// NSIS installer generator for Windows per-user installation
import { CarbonConfig } from "@carbon/contracts/app";

export async function generateNSIS(
  config: CarbonConfig,
  binaryPath: string,
  outputDir: string,
): Promise<string> {
  const appName = config.app.display_name || config.app.name;
  const version = config.app.version;

  const nsiScript = `
; NSIS Installer for ${appName}
; Generated by carbon bundle

!include "MUI2.nsh"

; General Settings
Name "${appName} ${version}"
OutFile "${outputDir}/${appName}-${version}-setup.exe"
InstallDir "$LOCALAPPDATA\\Programs\\${appName}"
ShowInstDetails show

; UI Settings
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"

  ; Create slots directory and install launcher + binary
  CreateDirectory "$INSTDIR\\slots\\${version}"

  ; Copy launcher.exe (stub)
  File "launcher.exe"

  ; Copy binary and bundle
  File "${binaryPath}"
  File "bundle.qbc.zst"

  ; Write initial current.toml
  FileOpen $0 "$INSTDIR\\current.toml" w
  FileWrite $0 'active_slot = "${version}"$$\\r$$\\n'
  FileWrite $0 'previous_slot = $$\\\"$$\\n'
  FileWrite $0 'in_progress_count = 0$$\\r$$\\n'
  FileWrite $0 'last_successful_version = "${version}"$$\\r$$\\n'
  FileClose $0

  ; Create Start Menu shortcut
  CreateDirectory "$SMPROGRAMS\\${appName}"
  CreateShortcut "$SMPROGRAMS\\${appName}\\${appName}.lnk" "$INSTDIR\\launcher.exe"
SectionEnd

Section "Uninstall"
  RMDir /r "$INSTDIR"
  RMDir /r "$SMPROGRAMS\\${appName}"
SectionEnd
`;

  return nsiScript;
}
