"""Locates cargo on the host and freezes the absolute path into a constant.

WHY THIS EXISTS
---------------
The launcher used to search for cargo at run time — $CARGO_HOME/bin,
~/.cargo/bin, then PATH. That works under `bazel run` and fails under
`bazel test`, because Bazel scrubs the test environment: USERPROFILE, HOME and
CARGO_HOME are not passed through, so every lookup path evaluates to empty and
a perfectly well installed cargo reports as missing.

Observed exactly that:

    error: cargo not found.
      looked in: %CARGO_HOME%\\bin, %USERPROFILE%\\.cargo\\bin, %PATH%

with cargo 1.86.0 sitting in C:\\Users\\mauro\\.cargo\\bin the whole time.

Repository rules run during fetch, not during the test, and DO see the real
environment. So the search happens once, here, and the result is written into a
generated .bzl file the rules read at analysis time. The run-time search stays
as a fallback for the case where the machine changed since the last fetch.

The trade is that the resolved path is baked into the analysis cache: install a
new toolchain elsewhere and `bazel clean --expunge` (or a changed CARGO_HOME) is
needed to pick it up. That is the normal cost of host-toolchain detection, and
it is why the Bun toolchain downloads its binary instead — an option Rust does
not have here, for the reasons in defs.bzl.
"""

_TEMPLATE = '''"""Generated by //.tools/orchestration/bazel/cargo:repositories.bzl. Do not edit."""

# Absolute path to the cargo binary found on this host at fetch time, or "" when
# none was found. Empty is not a fetch failure: a tree with no Rust targets
# being built should still be able to load this file, so the error is raised by
# the launcher, at the point where cargo is actually needed, with a message that
# says how to install it.
CARGO_PATH = {cargo_path}

# What `cargo --version` reported, for the toolchain check.
CARGO_VERSION = {cargo_version}

# Absolute path to the source tree.
#
# `bazel run` sets BUILD_WORKSPACE_DIRECTORY and the launcher uses that. `bazel
# test` does not set it — the working directory is the execroot — so a relative
# --manifest-path resolves against the wrong tree and cargo reports
# "manifest path `.config\\rust\\Cargo.toml` does not exist" while the file is
# sitting right there in the source tree.
#
# Captured here for the same reason as CARGO_PATH: repository rules can see
# things a scrubbed test environment cannot.
WORKSPACE_ROOT = {workspace_root}
'''

def _find_cargo(repository_ctx):
    """Search order mirrors the launcher's, most specific first."""
    environ = repository_ctx.os.environ
    exe = "cargo.exe" if repository_ctx.os.name.startswith("windows") else "cargo"

    candidates = []

    # rustup's own location, which it does not always put on PATH.
    cargo_home = environ.get("CARGO_HOME")
    if cargo_home:
        candidates.append(repository_ctx.path(cargo_home + "/bin/" + exe))

    for var in ("USERPROFILE", "HOME"):
        home = environ.get(var)
        if home:
            candidates.append(repository_ctx.path(home + "/.cargo/bin/" + exe))

    for candidate in candidates:
        if candidate.exists:
            return str(candidate)

    # PATH last: a rustup-managed toolchain should win over a distro package,
    # because rustup is what the pinned version in .config/dependencies.json
    # refers to.
    from_path = repository_ctx.which("cargo")
    if from_path:
        return str(from_path)

    return ""

def _cargo_repository_impl(repository_ctx):
    cargo_path = _find_cargo(repository_ctx)

    version = ""
    if cargo_path:
        result = repository_ctx.execute([cargo_path, "--version"])
        if result.return_code == 0:
            version = result.stdout.strip()

    repository_ctx.file("BUILD.bazel", 'exports_files(["defs.bzl"])\n')
    repository_ctx.file(
        "defs.bzl",
        _TEMPLATE.format(
            cargo_path = repr(cargo_path.replace("\\", "/")),
            cargo_version = repr(version),
            workspace_root = repr(str(repository_ctx.workspace_root).replace("\\", "/")),
        ),
    )

cargo_repository = repository_rule(
    implementation = _cargo_repository_impl,
    # Re-run detection when any of these change, so installing or moving a
    # toolchain is picked up without an explicit clean.
    environ = ["CARGO_HOME", "USERPROFILE", "HOME", "PATH"],
    local = True,
    doc = "Finds cargo on the host and records its absolute path.",
)
