// Ed25519 keypairs, with the key-id derivation carbon uses to tag key files.
//
// Ported from V1 tools/signer/src/keypair.rs. The Rust used ed25519-dalek;
// this uses @noble/curves, which is pure TypeScript and produces identical
// bytes: dalek's `SigningKey::from_bytes` takes the same 32-byte seed noble
// treats as the private key, and both derive the public key by the RFC 8032
// procedure. Keys generated by either implementation verify under the other.

import { createHash, randomBytes } from "node:crypto";
import { ed25519 } from "@noble/curves/ed25519";

/** Bytes of a raw Ed25519 seed / public key. */
export const KEY_BYTES = 32;
/** Bytes of an Ed25519 signature. */
export const SIGNATURE_BYTES = 64;
/** Bytes of the truncated-SHA256 key identifier stamped into every key file. */
export const KEY_ID_BYTES = 8;

export class SigningKey {
  /** The 32-byte Ed25519 seed. dalek's `to_bytes()` returned this same value. */
  readonly seed: Uint8Array;
  readonly keyId: Uint8Array;

  constructor(seed: Uint8Array, keyId: Uint8Array) {
    if (seed.length !== KEY_BYTES) {
      throw new Error(`signing key must be ${KEY_BYTES} bytes, got ${seed.length}`);
    }
    this.seed = seed;
    this.keyId = keyId;
  }

  sign(message: Uint8Array): Uint8Array {
    return ed25519.sign(message, this.seed);
  }

  verifyingKey(): VerifyingKey {
    return new VerifyingKey(ed25519.getPublicKey(this.seed), this.keyId);
  }

  toBytes(): Uint8Array {
    return this.seed;
  }
}

export class VerifyingKey {
  readonly publicKey: Uint8Array;
  readonly keyId: Uint8Array;

  constructor(publicKey: Uint8Array, keyId: Uint8Array) {
    if (publicKey.length !== KEY_BYTES) {
      throw new Error(`verifying key must be ${KEY_BYTES} bytes, got ${publicKey.length}`);
    }
    this.publicKey = publicKey;
    this.keyId = keyId;
  }

  /** Throws on a bad signature, matching the Rust `Result<()>` contract. */
  verify(message: Uint8Array, signature: Uint8Array): void {
    if (signature.length !== SIGNATURE_BYTES) {
      throw new Error(`signature must be ${SIGNATURE_BYTES} bytes, got ${signature.length}`);
    }
    if (!ed25519.verify(signature, message, this.publicKey)) {
      throw new Error("signature verification failed");
    }
  }

  toBytes(): Uint8Array {
    return this.publicKey;
  }

  toBase64(): string {
    return Buffer.from(this.publicKey).toString("base64");
  }
}

/**
 * The key identifier written into every .pub/.key/.sig file: the first 8 bytes
 * of SHA-256 over the public key. It exists so a signature can name the key it
 * was produced with, not to add security — it is not a secret and not a MAC.
 */
export function deriveKeyId(publicKey: Uint8Array): Uint8Array {
  const hash = createHash("sha256").update(publicKey).digest();
  return new Uint8Array(hash.subarray(0, KEY_ID_BYTES));
}

export function generateKeypair(): { signingKey: SigningKey; verifyingKey: VerifyingKey } {
  const seed = new Uint8Array(randomBytes(KEY_BYTES));
  const publicKey = ed25519.getPublicKey(seed);
  const keyId = deriveKeyId(publicKey);

  return {
    signingKey: new SigningKey(seed, keyId),
    verifyingKey: new VerifyingKey(publicKey, keyId),
  };
}
