// Code Generator: Translates visual studio node hierarchy into
// clean, production-grade Carbon Native .ctsx code.

export type StudioComponentType =
  | "Window"
  | "Titlebar"
  | "VStack"
  | "HStack"
  | "Card"
  | "Heading"
  | "Text"
  | "Button"
  | "TextInput"
  | "Badge"
  | "Divider";

export interface StudioNode {
  readonly id: string;
  readonly type: StudioComponentType;
  readonly props: Record<string, any>;
  readonly children?: StudioNode[];
}

export interface CodeGeneratorOptions {
  appName?: string;
  targetOs?: "windows" | "macos" | "linux";
}

export class CodeGenerator {
  private static instance: CodeGenerator;

  static getInstance(): CodeGenerator {
    if (!CodeGenerator.instance) {
      CodeGenerator.instance = new CodeGenerator();
    }
    return CodeGenerator.instance;
  }

  generateCtsx(root: StudioNode, options: CodeGeneratorOptions = {}): string {
    const appName = options.appName || "App";
    const usedImports = new Set<string>();

    const jsxBody = this.renderNode(root, 2, usedImports);
    const importList = Array.from(usedImports).sort().join(", ");

    return `// Generated by Carbon Studio
// Target: Carbon Native (.ctsx)

import { ${importList} } from "@carbon/native";

export default function ${appName}() {
  return (
${jsxBody}
  );
}
`;
  }

  private renderNode(node: StudioNode, indentLevel: number, imports: Set<string>): string {
    imports.add(node.type);
    const indent = " ".repeat(indentLevel * 2);

    // Format props
    const propPairs: string[] = [];
    for (const [key, val] of Object.entries(node.props || {})) {
      if (val === undefined || val === null) continue;
      if (typeof val === "string") {
        propPairs.push(`${key}="${val.replace(/"/g, '\\"')}"`);
      } else if (typeof val === "boolean") {
        if (val) propPairs.push(key);
      } else {
        propPairs.push(`${key}={${JSON.stringify(val)}}`);
      }
    }

    const propsStr = propPairs.length > 0 ? " " + propPairs.join(" ") : "";

    if (!node.children || node.children.length === 0) {
      return `${indent}<${node.type}${propsStr} />`;
    }

    const childrenJsx = node.children
      .map((child) => this.renderNode(child, indentLevel + 1, imports))
      .join("\n");

    return `${indent}<${node.type}${propsStr}>\n${childrenJsx}\n${indent}</${node.type}>`;
  }

  getTemplates(): Record<string, StudioNode> {
    return {
      blank: {
        id: "root-window",
        type: "Window",
        props: { title: "Carbon Application", width: 800, height: 600 },
        children: [
          {
            id: "titlebar-1",
            type: "Titlebar",
            props: { title: "Carbon Application", showControls: true },
          },
          {
            id: "content-stack",
            type: "VStack",
            props: { padding: 24, gap: 16 },
            children: [
              {
                id: "heading-1",
                type: "Heading",
                props: { text: "Welcome to Carbon Native", level: 1 },
              },
              {
                id: "text-1",
                type: "Text",
                props: { text: "Start building your desktop app visually." },
              },
              {
                id: "btn-1",
                type: "Button",
                props: { label: "Get Started", variant: "primary" },
              },
            ],
          },
        ],
      },
      dashboard: {
        id: "root-window",
        type: "Window",
        props: { title: "Metrics Dashboard", width: 1024, height: 720 },
        children: [
          {
            id: "titlebar-1",
            type: "Titlebar",
            props: { title: "Metrics Dashboard", showControls: true },
          },
          {
            id: "main-hstack",
            type: "HStack",
            props: { gap: 16, padding: 20 },
            children: [
              {
                id: "sidebar-vstack",
                type: "VStack",
                props: { width: 220, gap: 10 },
                children: [
                  { id: "badge-status", type: "Badge", props: { label: "PRO TIER", variant: "success" } },
                  { id: "btn-nav1", type: "Button", props: { label: "Overview", variant: "secondary" } },
                  { id: "btn-nav2", type: "Button", props: { label: "Telemetry", variant: "ghost" } },
                ],
              },
              {
                id: "metrics-card",
                type: "Card",
                props: { flex: 1, padding: 24 },
                children: [
                  { id: "h-analytics", type: "Heading", props: { text: "Realtime Analytics", level: 2 } },
                  { id: "txt-desc", type: "Text", props: { text: "Streaming sub-millisecond telemetry." } },
                  { id: "divider-1", type: "Divider", props: {} },
                  { id: "btn-export", type: "Button", props: { label: "Export Report", variant: "primary" } },
                ],
              },
            ],
          },
        ],
      },
    };
  }
}
