#!/usr/bin/env python3
"""
Captures the V1 runtime's functionality surface as a baseline.

Run this BEFORE migrating anything, and again after, and diff. The migration
splits a 4,441-line mini.rs and a 32k-line crate graph into capabilities; the
one thing that must not change while that happens is what an app can call.

Three surfaces are captured, because each can be lost independently:

  host-functions.txt   the JS <-> Rust boundary. 139 globals a bundle may call.
                       Losing one is silent until an app in the wild breaks.
  cargo-features.txt   the feature flags. Each gates a chunk of binary size,
                       so a dropped flag is either a bloated binary or a
                       missing subsystem.
  env-vars.txt         the runtime's out-of-band switches — debug, timing,
                       test hooks. Undocumented anywhere else.

Usage:
    python .tools/validation/capture_baseline.py <path-to-V1> [--check]

    --check compares against the committed baselines and exits non-zero on
    any difference, which is what the migration is verified with.
"""

import argparse
import pathlib
import re
import sys

BASELINE_DIR = pathlib.Path(__file__).resolve().parent / "baselines"

# Every file that can register a host function. mini.rs and blitz.rs register
# the renderer-facing ones directly; host/native/ and api/ hold the rest.
HOST_SOURCE_GLOBS = [
    "carbon/host/native/*.rs",
    "carbon/api/*.rs",
    "carbon/runtime/mini.rs",
    "carbon/runtime/blitz.rs",
]


def _sources(v1: pathlib.Path) -> list[pathlib.Path]:
    found: list[pathlib.Path] = []
    for pattern in HOST_SOURCE_GLOBS:
        if "*" in pattern:
            found.extend(sorted(v1.glob(pattern)))
        else:
            candidate = v1 / pattern
            if candidate.exists():
                found.append(candidate)
    return found


def capture_host_functions(v1: pathlib.Path) -> str:
    """Every `__cm_*` name, with the module that owns it."""
    owner: dict[str, list[str]] = {}
    for path in _sources(v1):
        text = path.read_text(encoding="utf-8", errors="replace")
        rel = str(path.relative_to(v1)).replace("\\", "/")
        for name in sorted(set(re.findall(r'"(__cm_[a-z0-9_]+)"', text))):
            owner.setdefault(name, []).append(rel)

    lines = [
        "# Carbon host-function surface — the JS <-> Rust boundary.",
        "#",
        "# Generated by .tools/validation/capture_baseline.py. Every name here is",
        "# reachable from a bundle as a global, and an app in the wild may call any",
        "# of them. The migration is complete only when V2 exposes all of them.",
        "#",
        "# Format:  <name><TAB><source module(s)>",
        f"# Count:   {len(owner)}",
        "",
    ]
    lines += [f"{name}\t{','.join(files)}" for name, files in sorted(owner.items())]
    return "\n".join(lines) + "\n"


def capture_cargo_features(v1: pathlib.Path) -> str:
    """The [features] table of the runtime package."""
    manifest = (v1 / "carbon/runtime/Cargo.toml").read_text(encoding="utf-8")

    section = re.search(r"^\[features\]$(.*?)^\[", manifest, re.M | re.S)
    body = section.group(1) if section else ""

    # `name = [ ... ]`, possibly spanning lines.
    features = re.findall(r"^([a-z_][a-z0-9_-]*)\s*=\s*\[(.*?)\]", body, re.M | re.S)

    lines = [
        "# Cargo features of the carbon-runtime package.",
        "#",
        "# Each gates a subsystem AND a chunk of binary size — `gpu` alone is",
        "# 2.5 MB. A feature lost in the migration is either a bloated default",
        "# build or a subsystem that can no longer be turned on.",
        f"# Count:   {len(features)}",
        "",
    ]
    for name, deps in sorted(features):
        cleaned = " ".join(d.strip().strip('",') for d in deps.split(",") if d.strip())
        lines.append(f"{name}\t{cleaned}")
    return "\n".join(lines) + "\n"


def capture_env_vars(v1: pathlib.Path) -> str:
    """Out-of-band switches read from the environment."""
    names: set[str] = set()
    for path in (v1 / "carbon").rglob("*.rs"):
        # bin/ is cargo build output, not source.
        if "/bin/" in str(path).replace("\\", "/"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        names.update(re.findall(r'"((?:CM|CARBON)_[A-Z0-9_]+)"', text))

    lines = [
        "# Environment variables the runtime reads.",
        "#",
        "# Debug switches, timing output, and the test hooks the integration",
        "# tests depend on (CARBON_TEST_EXIT_MS, CM_SCREENSHOT, CM_DUMP).",
        "# Documented nowhere else, so losing one loses the ability to test.",
        f"# Count:   {len(names)}",
        "",
    ]
    lines += sorted(names)
    return "\n".join(lines) + "\n"


CAPTURES = {
    "host-functions.txt": capture_host_functions,
    "cargo-features.txt": capture_cargo_features,
    "env-vars.txt": capture_env_vars,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("v1", type=pathlib.Path, help="path to the V1 checkout")
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare against committed baselines instead of writing them",
    )
    args = parser.parse_args()

    v1 = args.v1.resolve()
    if not (v1 / "carbon").is_dir():
        print(f"[FAIL] {v1} does not look like a V1 checkout (no carbon/)")
        return 1

    BASELINE_DIR.mkdir(parents=True, exist_ok=True)
    differences = 0

    for filename, capture in CAPTURES.items():
        produced = capture(v1)
        target = BASELINE_DIR / filename

        if args.check:
            if not target.exists():
                print(f"[FAIL] {filename} has no committed baseline")
                differences += 1
                continue
            if target.read_text(encoding="utf-8") != produced:
                print(f"[FAIL] {filename} differs from the committed baseline")
                differences += 1
            else:
                print(f"[OK]   {filename}")
        else:
            target.write_text(produced, encoding="utf-8")
            count = sum(1 for l in produced.splitlines() if l and not l.startswith("#"))
            print(f"[OK]   wrote {filename} ({count} entries)")

    if args.check and differences:
        print(f"\n[!] {differences} baseline(s) differ.")
        return 1

    print("\n[+] Baseline capture complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
